name: Build Kernel for Samsung A52 (a52q)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Kernel
        run: |
          chmod +x scripts/*.sh
          export CONFIG_ENV=Profiles/a52q_oneui.env
          bash scripts/build.sh
